### ISSUE TITLE
Add "Pause on idle"?

### ISSUE THREAD

**Issue by wzulfikar** [wkaisertexas/ScreenTimeLapse#24]
Hey, thanks for creating this! ♥️

How difficult do you think to have a "Pause on idle" option? I want to test how long I can record with this so I'll activate it all the time. But I don't want to have those "idle" frames recorded which will make it difficult for me when I review. Something like:

- Pause recording if screen is locked, user is logged out, or machine is sleeping. Auto resume if unlocked, etc.
- Pause recording if no mouse activity in 5 minutes. Auto resume (and reset the timer) if there's mouse activity.

My Swift knowledge is very limited but I can dig. Although, if you have pointer, it'd be great!

**Comment by wkaisertexas** [comment]
## Pausing Recording on Logoout

It has been a while since I tested this, but I think everything is based on presentation time stamps. So, if you are logged out, your presentation time stamp is not increasing. Therefore, you should not be contributing to an increased bitcount. 

---

## Determining new information per frame

Determining whether or not a frame contains new information should not be too bad. There is something called dirty rects which is given by ScreenCaptureKit and contains an array of rectangles that have changed on the screen every frame. 

[Documentation on Dirty Rects](https://developer.apple.com/documentation/screencapturekit/scstreamframeinfo#:~:text=static%20let%20dirtyRects%3A%20SCStreamFrameInfo)

Checking if the length of the dirty rects list is zero would be all that is required to not save these frames. 

This could be as simple as adding a check in the `appendBuffer` function in the file `Recordable.swift`
