### ISSUE TITLE
Multiple issues on MacOS 15.0.1

### ISSUE THREAD

**Issue by Tekorius** [wkaisertexas/ScreenTimeLapse#52]
I'm running MacOS 15.0.1. Installed application through homebrew. I have found multiple issues when testing the application

I can create separate issues for them if you want to track them separately:

- When I press "Choose Output Folder" in settings nothing happens.
- When choosing FPS the dropdown still shows 30 fps, but when dropdown is opened 25 fps is ticked. The video is recorded with correct FPS so it seems it's just a UI issue.
- Quality setting either doesn't do anything or is inverted. When choosing high the video is the worst. Medium seems to produce best results.
- Video quality gets destroyed on high time multipliers. I tried recording at 60x, when there's a lot of movement, the quality dips so low, the text is ineligible. This might have something to do with codec. Maybe lower the key frame interval.
- Enabled apps and settings like "show cursor" are not persisted between restarts.
- Videos stay in `tmp` folder. I don't know whether they should be moved out, but all recorded videos stay in `~/Library/Containers/com.smartservices.TimeLapze/Data/tmp`
- When timelapze is open, choosing settings from the top bar does not bring application to focus.

**Comment by wkaisertexas** [comment]
- When I press "Choose Output Folder" in settings nothing happens.

This was an issue that got fixed but the patch was not pushed to homebrew yet

- When choosing FPS the dropdown still shows 30 fps, but when dropdown is opened 25 fps is ticked. The video is recorded with correct FPS so it seems it's just a UI issue.

This is new and I will have to look further into this.

- Quality setting either doesn't do anything or is inverted. When choosing high the video is the worst. Medium seems to produce best results.

I am not sure what this is. The low, medium and high values get fed through to Apple's AVFoundation directly which makes this very strange.

- Video quality gets destroyed on high time multipliers. I tried recording at 60x, when there's a lot of movement, the quality dips so low, the text is ineligible. This might have something to do with codec. Maybe lower the key frame interval.

The higher the speed multiple the more frames change from frame to frame. Videos save a lot of bitrate because videos tend to not change too much from frame to frame, so they do not need to state the data again.

With that being said, your bistrate should increase with an increasing time multiple. This should be setup.

- Enabled apps and settings like "show cursor" are not persisted between restarts.

This is something that I have planned for next update. I think it may have even been merged, but I have not gone through the process of making a new release.

- Videos stay in tmp folder. I don't know whether they should be moved out, but all recorded videos stay in ~/Library/Containers/com.smartservices.TimeLapze/Data/tmp
When timelapze is open, choosing settings from the top bar does not bring application to focus.

So, I can only save to the tmp folder if you do not select a video. My workaround to this was always opening the video if the user save location was the tmp folder. 

Why not just use the Videos directory? Whelp, I got into a long fight with the app store review people about initially having this permission on my Application. However, they simply refused to let me update my application until this took place which is so frustrating. 

If more things happen like this in the future, I may consider creating a new build for homebrew.

---

I have been a student, and so I will try and push these updates over fall break when I have the time. Sorry about that. 

These are good suggestions, specifically how common codecs may not hold up at a constant bit rate. I may have to look into:

- [Encoder Bit Rate Strategy Values](https://developer.apple.com/documentation/avfoundation/audio_settings/encoder_bit_rate_strategy_values) and how to specify a variable bit rate

I may also want to lower the default frame rate because I have been finding the videos that I record at high frame rates can tend to be a bit too flashy.

**Comment by Tekorius** [comment]
No worries, take your time, studies comes first. I can help test some features and report my findings. I have been looking for a painless way to do design timelapses for my youtube channel, that's how I've stumbled upon your project.

Unfortunately I'm not familiar with Mac APIs and what it offers, but right now I'm using OBS to record 1 fps videos, which seems to work fine.

In OBS, I am using Apple VT HEVC Hardware encoder, with rate control set to CRF (as opposed to CBR), 80% quality, keyframe interval of 1s, and main10 profile. I don't know if any of these settings helps you to fine tune the encoder, but just sharing what I use. These settings produce clips of ~16 MB / minute at 1440p resolution at 1 fps.

**Comment by wkaisertexas** [comment]
How many megabytes per minute do you get from time lapze? Is the quality
that much worse?

Also what color space are you recording in?

**Comment by wkaisertexas** [comment]
The resolution is twice your normal resolution. This is because macs and tend to lie about their actual resolution because they have a pixel ratio of two. However, some external monitors do not do this

**Comment by wkaisertexas** [comment]
#58 Resolves all of these issues. It will take me a few days to push a new build, so the updates will not be applied right away.

Thank you for all the feedback.
