### ISSUE TITLE
App would start after install via Homebrew

### ISSUE THREAD

**Issue by Christian-Marc** [wkaisertexas/ScreenTimeLapse#7]
I'm working on a Sonoma 14.1 and after installation application won't start. If look if there are security issues in the system settings (not shown), so it is not blocked. 

Can you give advice to try it out?
Marc

<img width="937" alt="Scherm­afbeelding 2023-11-12 om 08 32 55" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/5346385/aa09ee08-bfaf-4027-bc64-433dd061377e">
<img width="406" alt="Scherm­afbeelding 2023-11-12 om 08 33 18" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/5346385/f2cb4ae8-2d5f-40a5-a426-efbc347db594">

**Comment by wkaisertexas** [comment]
Thank you for brining this to my attention.

Apparently, there is a difference between zipping a folder on your computer and uploading it and uploading the `.app` file to GitHub directly. Going the direct route bricks the installation for some reason. 

You should be able to reinstall with `brew`. However, since a new version was not released, you might have to remove homebrew's cache. 

```bash
brew uninstall --ignore-dependencies --force ScreenTimeLapse; rm -rf ~/.cask/ScreenTimeLapse
```

> Note: I don't pay the $99 a year for Apple Developer so it will say "can't be checked for malicious software". However, you can ignore that in your system settings.
